name: photo_sweeper
description: "A new Flutter project."
publish_to: 'none' 
version: 0.1.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # For i18n
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.2
  
  # State Management
  hooks_riverpod: ^2.4.9
  flutter_hooks: ^0.20.3
  
  # Immutability
  freezed_annotation: ^2.4.1

  # Routing
  go_router: ^12.1.1

  # Internationalization
  intl: ^0.20.2
  
  # Photos
  photo_manager: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.5
  
  # Lints
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true # Enables i18n generation